name: Codetech @ Leg Godt
favicon: null
layout_spectrum: 1
typography_spectrum: 1
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#11110f'
    - '#a28f6e'
    - '#2f5dab'
    - '#e74f38'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
