layout_spectrum: 1
favicon: null
name: Codetech @ Leg Godt
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.25
  brandColors:
    - '#ffffff'
    - '#11110f'
    - '#a28f6e'
    - '#2f5dab'
    - '#e74f38'
typography_spectrum: 0.8078849
